### PR TITLE
add one class like helloworld

### PR DESCRIPTION
**Pull request by atchuthautomation**
I have to added to one class please approve my code boss....

### CODE REVIEW

**Comment by atchuthautomation** [comment]
Please check my code

**Comment by Devicky125143** [comment]
kk atchuth but add the one printing statement

**Comment by atchuthautomation** [comment]
Kk boss

**Comment by atchuthautomation** [comment]
I added the one class check once

**Comment by Devicky125143** [comment]
kk merge the branches

**Pull request merged**
